install_data(
  'hicolor/scalable/apps/im.apodaca.SqlatorGtk.svg',
  install_dir: join_paths(get_option('datadir'), 'icons', 'hicolor', 'scalable', 'apps'),
)

install_data(
  'hicolor/symbolic/apps/im.apodaca.SqlatorGtk-symbolic.svg',
  install_dir: join_paths(get_option('datadir'), 'icons', 'hicolor', 'symbolic', 'apps'),
)
